title: Argentina y Conquista del Río de la Plata 
email: hdlabconicet@gmail.com
description: con otros acaecimientos de los reinos del Perú, Tucumán y el Estado del Brasil
baseurl: "/argentina-y-conquista-del-rio-de-la-plata"
url: "https://hdlab.space"
github_repo: argentina-y-conquista-del-rio-de-la-plata/
twitter_username: hdlabconicet
github_username:  hdcaicyt
facebook_username: hdlabconicet

social_link: twitter
social_username: hdlabconicet

theme_color: light

# Build settings
markdown: kramdown

collections:
    barco_centenera_pages:
      output: true
    recursos:
      output: true
