title: Argentina y Conquista del Río de la Plata 
email: hdcaicyt@gmail.com
description: con otros acaecimientos de los reinos del Perú, Tucumán y el Estado del Brasil
baseurl: "/argentina-y-conquista-del-rio-de-la-plata" # the subpath of your site, e.g. /blog
url: "http://hdlab.space" # the base hostname & protocol for your site
github_repo: argentina-y-conquista-del-rio-de-la-plata/ # the GitHub repo name for your project
twitter_username: HDCAICYT
github_username:  hdcaicyt
facebook_username: HDCAICYTLAB

social_link: twitter
social_username: hdcaicyt

theme_color: light

# Build settings
markdown: kramdown

collections:
    barco_centenera_pages:
      output: true
    recursos:
      output: true
